ls:
  .dir: kebab-case | regex:(\.*([a-z])[A-Z]*)+ | regex:(__([a-z]*)__)+
  .js: kebab-case | regex:(\.*([a-z])[A-Z]*)+
  .config.js: kebab-case
  .setup.js: kebab-case
  .ts: kebab-case | camelCase
  .test.ts: camelCase | PascalCase
  .d.ts: kebab-case
  .tsx: camelCase | PascalCase
  .page.tsx: camelCase | PascalCase
  .stories.tsx: camelCase | PascalCase
  .test.tsx: camelCase | PascalCase
  .yml: kebab-case | regex:(\.*([a-z])(-[a-z])*)+
  .md: snake_case | SCREAMING_SNAKE_CASE | kebab-case | PascalCase

ignore:
  - .idea
  - .github/ISSUE_TEMPLATE
  - .husky
  - node_modules
  - docs/_config.yml
  - frontend/.next
  - frontend/build
  - frontend/coverage
  - frontend/node_modules
  - frontend/out
  - frontend/src/pages/_app.page.tsx
