name: Build Frontend

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Run lint
        run: yarn lint
      - name: Run prettier
        run: yarn prettier
      - name: Run tests
        run: yarn test:ci --coverage
      - name: Build app
        run: yarn build
      - name: Upload coverage to Codecov
        # TODO: Re-add this
        # if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
