name: Coverage Frontend

on:
  push:
    branches:
      # TODO: Delete this
      - feat/codecov
      - main
    # TODO: Re-add this
    # paths:
    #   - 'frontend/**'

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
